import type { BlipPose } from "./blip.params";

/**
 * Blip's pose table, ported verbatim from spec section 5.4. Every row is one
 * of the 22 launch items, in the spec's own order (also the pack's item
 * order and `BlipItemId`'s declaration order). The spec's `tilt` column
 * becomes `tiltDeg` here, matching `BlipPose`.
 *
 * The Facepalm pose is parked and is not part of this table: `BlipItemId`
 * never names it, so it can never reach `blipGeometry` or the item catalog.
 */
export const BLIP_POSES: readonly BlipPose[] = [
  {
    id: "hi",
    eyes: "bean",
    mouth: "smile",
    antenna: "steady",
    arms: "wave",
    extras: ["blush"],
  },
  {
    id: "yay",
    squash: 1.15,
    eyes: "stars",
    mouth: "grin",
    antenna: "spike",
    arms: "up",
    extras: ["sparkles"],
  },
  {
    id: "crying-laughing",
    squash: 1.28,
    eyes: "arcs",
    mouth: "laugh",
    antenna: "spike",
    extras: ["tears", "blush"],
  },
  {
    id: "love",
    eyes: "hearts",
    mouth: "smile",
    antenna: "heart",
    extras: ["blush", "floatHearts"],
  },
  {
    id: "shocked",
    squash: 0.74,
    eyes: "wide",
    mouth: "o",
    antenna: "exclaim",
    extras: ["sweat"],
  },
  {
    id: "side-eye",
    tiltDeg: -8,
    eyes: "half",
    look: [13, 0],
    brows: "raised",
    mouth: "smirk",
    antenna: "steady",
  },
  {
    id: "sad",
    melt: 0.5,
    squash: 1.06,
    eyes: "teary",
    brows: "worried",
    mouth: "frown",
    antenna: "droop",
  },
  {
    id: "hug",
    eyes: "arcs",
    mouth: "smile",
    antenna: "heart",
    arms: "hug",
    extras: ["blush"],
    faceDrop: -14,
  },
  {
    id: "thinking",
    eyes: "bean",
    look: [8, -12],
    mouth: "flat",
    antenna: "question",
    arms: "chin",
    faceShift: -10,
  },
  {
    id: "sleepy",
    squash: 1.08,
    eyes: "closed",
    mouth: "small",
    antenna: "wave",
    extras: ["zzz", "blush"],
  },
  {
    id: "shy",
    eyes: "bean",
    look: [-6, 10],
    mouth: "wobbly",
    antenna: "steady",
    arms: "together",
    extras: ["bigBlush"],
  },
  {
    id: "sipping-tea",
    eyes: "half",
    mouth: "none",
    antenna: "steady",
    arms: "cup",
  },
  {
    id: "thank-you",
    eyes: "arcs",
    mouth: "smile",
    antenna: "heart",
    arms: "together",
    extras: ["sparkles", "blush"],
  },
  {
    id: "sorry",
    eyes: "teary",
    look: [0, 6],
    brows: "worried",
    mouth: "wobbly",
    antenna: "droop",
    arms: "together",
    extras: ["sweat"],
  },
  {
    id: "hmph",
    eyes: "closed",
    brows: "determined",
    mouth: "pout",
    antenna: "angry",
    extras: ["steam"],
  },
  {
    id: "party",
    squash: 1.1,
    eyes: "arcs",
    mouth: "grin",
    antenna: "spike",
    arms: "up",
    extras: ["confetti", "blush"],
  },
  {
    id: "proud",
    squash: 0.88,
    eyes: "arcs",
    mouth: "smirk",
    antenna: "steady",
    arms: "hips",
    extras: ["sparkles"],
  },
  {
    id: "fan-clack",
    eyes: "half",
    look: [-10, 0],
    mouth: "cat",
    antenna: "spike",
    arms: "fan",
    faceShift: -16,
  },
  {
    id: "shrug",
    eyes: "half",
    brows: "up",
    mouth: "wobbly",
    antenna: "question",
    arms: "shrug",
  },
  {
    id: "on-my-way",
    tiltDeg: 10,
    eyes: "bean",
    look: [10, 0],
    brows: "determined",
    mouth: "grin",
    antenna: "spike",
    extras: ["motion"],
  },
  {
    id: "home-safe",
    eyes: "arcs",
    mouth: "smile",
    antenna: "heart",
    prop: "house",
    extras: ["blush"],
  },
  {
    id: "melting",
    melt: 1.4,
    squash: 1.12,
    eyes: "half",
    look: [0, 4],
    mouth: "tongue",
    antenna: "droop",
    extras: ["heat", "sweat"],
  },
];
