import type { SubprofileKind, SubprofileSection } from "./api/subprofiles.api";

// ── Kinds & sections config (contract C1 — verbatim, mirrored on the backend) ─
//
// Kept in its own import-free module (types only) so
// `scripts/check-work-taxonomy.mjs` can transpile and load it alone and
// compare it with the backend's `subprofiles/subprofile-kinds.ts`.
// `subprofile-kinds.ts` re-exports it, so callers import it from there.

/** kind -> ordered content sections (excludes the universal 'links'). */
export const KIND_SECTIONS: Record<SubprofileKind, SubprofileSection[]> = {
  developer: ["projects", "open_source"],
  writer: ["publications", "readings"],
  musician: ["discography", "gigs"],
  visual_artist: ["portfolio", "exhibitions"],
  filmmaker: ["filmography", "screenings"],
  designer: ["selected_work", "clients"],
  maker: ["collections", "workshops"],
  drag: ["shows", "looks"],
  dj: ["mixes", "gigs"],
  dancer: ["performances", "reel"],
  performer: ["appearances", "reel"],
  photographer: ["series", "exhibitions"],
  videomaker: ["videos", "screenings"],
  video_creator: ["videos", "series"],
  short_form_creator: ["videos", "campaigns"],
  chef: ["menus", "residencies"],
  mixologist: ["cocktails", "residencies"],
  therapist: ["specialisms", "credentials"],
  astrologer: ["charts", "sky"],
  generic: ["showcase"],
  // stage (new kinds)
  comedian: ["sets", "tour"],
  vocalist: ["recordings", "gigs"],
  burlesque: ["acts", "looks"],
  circus: ["acts", "reel"],
  spoken_word: ["pieces", "readings"],
  host: ["hosted", "appearances"],
  voguer: ["balls", "reel"],
  pole_dancer: ["performances", "classes", "reel", "workshops"],
  // studio (new kinds)
  illustrator: ["portfolio", "clients"],
  tattoo_artist: ["flash", "healed"],
  animator: ["reel", "clients"],
  comic_artist: ["books", "strips"],
  game_designer: ["games", "jams"],
  artist_3d: ["models", "clients"],
  printmaker: ["editions", "workshops"],
  // page (new kinds)
  journalist: ["reporting", "bylines"],
  poet: ["poems", "readings"],
  editor: ["edited", "clients"],
  screenwriter: ["scripts", "productions"],
  translator: ["translations", "languages"],
  zinester: ["zines", "distros"],
  academic: ["papers", "teaching"],
  // workshop (new kinds)
  ceramicist: ["wares", "firings"],
  jeweler: ["pieces", "commissions"],
  textile_artist: ["pieces", "workshops"],
  woodworker: ["builds", "commissions"],
  florist: ["arrangements", "events"],
  data_scientist: ["analyses", "open_source"],
  // practice (new kinds)
  coach: ["programmes", "credentials"],
  bodyworker: ["treatments", "credentials"],
  yoga_teacher: ["classes", "trainings"],
  nutritionist: ["specialisms", "credentials"],
  doula: ["support", "credentials"],
  personal_trainer: ["training", "credentials"],
  sex_educator: ["workshops", "resources"],
  peer_support: ["groups", "credentials"],
  // table (new kinds)
  baker: ["bakes", "markets"],
  barista: ["brews", "residencies"],
  brewer: ["releases", "taprooms"],
  sommelier: ["lists", "pairings"],
  caterer: ["menus", "events"],
  // chair (new family)
  hair_stylist: ["services", "looks"],
  barber: ["services", "cuts"],
  makeup_artist: ["looks", "clients"],
  nail_artist: ["nail_sets", "services"],
  esthetician: ["treatments", "aftercare"],
  piercer: ["piercings", "aftercare"],
  // runway (new family)
  fashion_designer: ["collections", "shows"],
  stylist: ["editorials", "clients"],
  model: ["book", "campaigns"],
  costume_designer: ["productions", "sketches"],
  // gallery (new family)
  curator: ["exhibitions", "texts"],
  gallerist: ["programme", "artists"],
  art_dealer: ["available", "advisory"],
  archivist: ["collections", "finding_aids"],
  conservator: ["treatments", "credentials"],
  registrar: ["collections", "loans"],
  exhibition_designer: ["installations", "clients"],
  art_critic: ["reviews", "publications"],
  docent: ["tours", "talks"],
  preparator: ["installs", "clients"],
  // history (new family — "Record")
  historian: ["research", "publications"],
  art_historian: ["research", "lectures"],
  oral_historian: ["testimonies", "projects"],
  genealogist: ["services", "findings"],
  heritage: ["sites", "campaigns"],
  archival_researcher: ["research", "finding_aids"],
  memory_keeper: ["projects", "testimonies"],
  // collective (new family — "Poster")
  organizer: ["campaigns", "actions"],
  activist: ["campaigns", "writing"],
  event_producer: ["events", "clients"],
  promoter: ["nights", "roster"],
  // classroom (new family)
  teacher: ["courses", "resources"],
  facilitator: ["workshops", "clients"],
  tutor: ["subjects", "courses"],
  lecturer: ["courses", "papers"],
  // Quest personas (+20). Identical mapping to the backend mirror.
  game_master: ["campaigns", "sessions"],
  ttrpg_designer: ["games", "jams"],
  board_game_reviewer: ["reviews", "playthroughs"],
  game_night_host: ["nights", "library"],
  larp_organizer: ["larps", "workshops"],
  miniature_painter: ["minis", "commissions"],
  cartographer: ["maps", "commissions"],
  dice_maker: ["dice", "commissions"],
  tournament_organizer: ["events", "results"],
  actual_play: ["shows", "appearances"],
  streamer: ["streams", "videos"],
  speedrunner: ["runs", "videos"],
  modder: ["mods", "open_source"],
  cosplayer: ["builds", "cons"],
  prop_maker: ["builds", "commissions"],
  puzzle_designer: ["puzzles", "events"],
  podcaster: ["episodes", "appearances"],
  podcast_producer: ["productions", "clients"],
  radio_host: ["episodes", "appearances"],
  voice_actor: ["reel", "roles"],
  fanfic_writer: ["works", "series"],
  game_critic: ["reviews", "publications"],
};
