// Stable machine error codes (docs/backend/13). The frontend switches on these,
// never on message text or status. Add codes here in the PR that introduces them.

export const AppErrorCode = {
  // cross-cutting
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  IDEMPOTENCY_CONFLICT: 'IDEMPOTENCY_CONFLICT',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
  UNSUPPORTED_MEDIA_TYPE: 'UNSUPPORTED_MEDIA_TYPE',
  BAD_REQUEST: 'BAD_REQUEST',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  INTERNAL: 'INTERNAL',

  // auth / accounts
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TWO_FACTOR_REQUIRED: 'TWO_FACTOR_REQUIRED',
  TWO_FACTOR_INVALID: 'TWO_FACTOR_INVALID',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  ACCOUNT_PENDING_REVIEW: 'ACCOUNT_PENDING_REVIEW',
  ACCOUNT_SUSPENDED: 'ACCOUNT_SUSPENDED',
  ACCOUNT_BANNED: 'ACCOUNT_BANNED',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_CONSUMED: 'TOKEN_CONSUMED',
  REFRESH_REUSE_DETECTED: 'REFRESH_REUSE_DETECTED',
  INVITE_INVALID: 'INVITE_INVALID',
  INVITE_EXPIRED: 'INVITE_EXPIRED',
  INVITE_EXHAUSTED: 'INVITE_EXHAUSTED',
  WEAK_PASSWORD: 'WEAK_PASSWORD',
  EMAIL_TAKEN: 'EMAIL_TAKEN',
  HANDLE_TAKEN: 'HANDLE_TAKEN',

  // social
  ALREADY_VOUCHED: 'ALREADY_VOUCHED',
  BLOCKED: 'BLOCKED',

  // moderation
  ALREADY_REPORTED: 'ALREADY_REPORTED',
  APPEAL_ALREADY_DECIDED: 'APPEAL_ALREADY_DECIDED',

  // gatherings
  GATHERING_FULL: 'GATHERING_FULL',
  GATHERING_CANCELLED: 'GATHERING_CANCELLED',
  ALREADY_RSVPED: 'ALREADY_RSVPED',
  RSVP_NOT_FOUND: 'RSVP_NOT_FOUND',
  INVALID_PRICE: 'INVALID_PRICE',
  AMOUNT_BELOW_FLOOR: 'AMOUNT_BELOW_FLOOR',

  // payments
  PAYMENTS_DISABLED: 'PAYMENTS_DISABLED',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  WEBHOOK_SIGNATURE_INVALID: 'WEBHOOK_SIGNATURE_INVALID',

  // media
  UPLOAD_REJECTED: 'UPLOAD_REJECTED',
  MEDIA_NOT_READY: 'MEDIA_NOT_READY',
} as const
export type AppErrorCode = (typeof AppErrorCode)[keyof typeof AppErrorCode]

const ALL_CODES = new Set<string>(Object.values(AppErrorCode));

export function isAppErrorCode(value: unknown): value is AppErrorCode {
  return typeof value === 'string' && ALL_CODES.has(value);
}

/** The uniform error envelope returned by the API (docs/backend/02 §2.7). */
export interface AppErrorEnvelope {
  error: {
    code: AppErrorCode;
    message: string;
    details?: { field: string; issue: string }[] | unknown;
    correlationId: string;
    statusCode: number;
  };
}
