import { beforeEach, describe, expect, it } from "vitest";
import type { ChatMessage } from "./data";
import {
  clearOutbox,
  getActiveOutboxStorageKey,
  loadOutbox,
  peekOutbox,
  readUnseenOutboxEntries,
  saveOutbox,
  setMessageOutboxScope,
  writeOutboxRaw,
} from "./outbox";

// ENG-263: unit coverage for the persisted offline-outbox store itself
// (localStorage read/write/merge). Every test uses its OWN scope string,
// generated by `uniqueId`, so distinct tests never collide on the same
// storage key, and every localId is minted fresh (never reused across
// tests) since `knownLocalIds` (the cross-tab bookkeeping set in
// `outbox.ts`) is module-scoped and never reset. Reusing an id across
// tests would leak whether it's "known" from one test into the next.

let idSeq = 0;
function uniqueId(prefix: string): string {
  idSeq += 1;
  return `${prefix}-${idSeq}`;
}

function buildMessage(overrides: Partial<ChatMessage> = {}): ChatMessage {
  return {
    from: "me",
    text: "hello",
    localId: uniqueId("msg"),
    ...overrides,
  };
}

beforeEach(() => {
  window.localStorage.clear();
  setMessageOutboxScope(null);
});

describe("storage key scoping", () => {
  it("uses the base key when there's no scope, or the demo scope", () => {
    setMessageOutboxScope(null);
    expect(getActiveOutboxStorageKey()).toBe("qp.messages.outbox.v1");
    setMessageOutboxScope("demo");
    expect(getActiveOutboxStorageKey()).toBe("qp.messages.outbox.v1");
  });

  it("suffixes the key with a live member scope", () => {
    setMessageOutboxScope("member-42");
    expect(getActiveOutboxStorageKey()).toBe(
      "qp.messages.outbox.v1.u.member-42",
    );
  });
});

describe("saveOutbox / loadOutbox", () => {
  it("round-trips a valid outbox entry through the store", () => {
    setMessageOutboxScope(uniqueId("scope"));
    const convId = uniqueId("conv");
    const message = buildMessage({ text: "hi there", status: "sending" });

    saveOutbox({ [convId]: [message] });

    expect(loadOutbox()[convId]).toEqual([message]);
  });

  it("keeps the identity an entry was composed as through a round-trip", () => {
    const scope = uniqueId("scope");
    setMessageOutboxScope(scope);
    const convId = uniqueId("conv");
    const message = buildMessage({
      status: "sending",
      sendAsIdentityId: "identity-cafe",
    });

    saveOutbox({ [convId]: [message] });

    expect(loadOutbox(scope)[convId]?.[0]?.sendAsIdentityId).toBe(
      "identity-cafe",
    );
  });

  it("drops entries that don't look like a ChatMessage, tolerating a corrupt/foreign shape", () => {
    const scope = uniqueId("scope");
    setMessageOutboxScope(scope);
    const convId = uniqueId("conv");
    window.localStorage.setItem(
      getActiveOutboxStorageKey(),
      JSON.stringify({
        [convId]: [
          { from: "me", text: "missing localId" },
          {
            from: "someone-else",
            text: "bad from field",
            localId: uniqueId("bad"),
          },
          { from: "me", localId: uniqueId("bad2") }, // missing text
          buildMessage({ text: "the one valid entry" }),
        ],
      }),
    );

    const loaded = loadOutbox(scope);
    expect(loaded[convId]).toHaveLength(1);
    expect(loaded[convId]?.[0]?.text).toBe("the one valid entry");
  });

  it("tolerates corrupt JSON, returning an empty outbox rather than throwing", () => {
    const scope = uniqueId("scope");
    setMessageOutboxScope(scope);
    window.localStorage.setItem(getActiveOutboxStorageKey(), "not json{");
    expect(loadOutbox(scope)).toEqual({});
  });

  it("strips a dead blob: preview at save time, but keeps sendAttachment", () => {
    setMessageOutboxScope(uniqueId("scope"));
    const convId = uniqueId("conv");
    const message = buildMessage({
      kind: "image",
      attachment: {
        url: "blob:local-preview",
        previewUrl: "blob:local-preview",
        width: 100,
        height: 100,
        provider: "upload",
      },
      sendAttachment: {
        url: "uploads/real-key",
        previewUrl: "uploads/real-key",
        width: 100,
        height: 100,
        provider: "upload",
      },
    });

    saveOutbox({ [convId]: [message] });

    const loaded = loadOutbox()[convId]?.[0];
    expect(loaded?.attachment).toBeUndefined();
    expect(loaded?.sendAttachment).toEqual(message.sendAttachment);
  });

  it("removes an emptied conversation's key from storage entirely, once this tab's copy is known", () => {
    setMessageOutboxScope(uniqueId("scope"));
    const convId = uniqueId("conv");
    saveOutbox({ [convId]: [buildMessage()] });
    expect(
      window.localStorage.getItem(getActiveOutboxStorageKey()),
    ).not.toBeNull();

    // This tab no longer holds the entry (delivered/migrated/replaced): not
    // resurrected on the next save.
    saveOutbox({});
    expect(window.localStorage.getItem(getActiveOutboxStorageKey())).toBeNull();
  });

  it("preserves another tab's still-unseen entry through the cross-tab merge, without dropping this tab's own update", () => {
    setMessageOutboxScope(uniqueId("scope"));
    const convId = uniqueId("conv");
    const mine = buildMessage({ text: "mine" });
    saveOutbox({ [convId]: [mine] }); // marks `mine` known and persists it

    // Another tab appends its own still-queued send directly to storage,
    // bypassing this tab's saveOutbox entirely. This tab never sees it via
    // load/save, so it stays unknown.
    const theirs = buildMessage({
      text: "theirs",
      at: "2026-01-01T00:00:00.000Z",
    });
    window.localStorage.setItem(
      getActiveOutboxStorageKey(),
      JSON.stringify({ [convId]: [mine, theirs] }),
    );

    // This tab's own state only knows about an EDITED `mine`; the merge must
    // still preserve the foreign, unseen `theirs` entry rather than
    // clobbering it.
    const mineEdited = { ...mine, text: "mine, edited" };
    saveOutbox({ [convId]: [mineEdited] });

    const loaded = loadOutbox()[convId] ?? [];
    const localIds = loaded.map((entry) => entry.localId).sort();
    expect(localIds).toEqual([mine.localId, theirs.localId].sort());
    expect(loaded.find((entry) => entry.localId === mine.localId)?.text).toBe(
      "mine, edited",
    );
  });
});

describe("peekOutbox", () => {
  it("never marks its results known, unlike loadOutbox", () => {
    const scope = uniqueId("scope");
    setMessageOutboxScope(scope);
    const convId = uniqueId("conv");
    const message = buildMessage();
    // Written as if by another tab, reachable here only through peekOutbox.
    window.localStorage.setItem(
      getActiveOutboxStorageKey(),
      JSON.stringify({ [convId]: [message] }),
    );

    peekOutbox(scope); // must NOT mark it known
    saveOutbox({}); // this tab's own state still holds nothing
    expect(loadOutbox(scope)[convId]).toEqual([message]); // preserved: still unseen

    loadOutbox(scope); // NOW marks it known
    saveOutbox({}); // this tab's own state holds nothing again
    expect(loadOutbox(scope)[convId]).toBeUndefined(); // dropped: known and no longer held
  });
});

describe("writeOutboxRaw", () => {
  it("writes exactly what it's given, with no cross-tab merge", () => {
    const scope = uniqueId("scope");
    setMessageOutboxScope(scope);
    const convId = uniqueId("conv");
    const foreign = buildMessage(); // pre-existing entry this tab never saw
    window.localStorage.setItem(
      getActiveOutboxStorageKey(),
      JSON.stringify({ [convId]: [foreign] }),
    );

    const mine = buildMessage();
    writeOutboxRaw({ [convId]: [mine] }, scope);

    const loaded = loadOutbox(scope)[convId] ?? [];
    expect(loaded.map((entry) => entry.localId)).toEqual([mine.localId]);
  });
});

describe("clearOutbox", () => {
  it("removes only the currently active scope's key", () => {
    const scopeA = uniqueId("scope-a");
    const scopeB = uniqueId("scope-b");

    setMessageOutboxScope(scopeA);
    saveOutbox({ [uniqueId("conv")]: [buildMessage()] });

    setMessageOutboxScope(scopeB);
    saveOutbox({ [uniqueId("conv")]: [buildMessage()] });

    setMessageOutboxScope(scopeA);
    clearOutbox();
    expect(window.localStorage.getItem(getActiveOutboxStorageKey())).toBeNull();

    setMessageOutboxScope(scopeB);
    expect(
      window.localStorage.getItem(getActiveOutboxStorageKey()),
    ).not.toBeNull();
  });
});

describe("readUnseenOutboxEntries", () => {
  it("returns only entries this tab has never known, sorted oldest-first, and marks them known", () => {
    setMessageOutboxScope(uniqueId("scope"));
    const convId = uniqueId("conv");
    const known = buildMessage({ text: "known" });
    saveOutbox({ [convId]: [known] }); // marks `known` known

    const newer = buildMessage({
      text: "newer",
      at: "2026-02-02T00:00:00.000Z",
    });
    const older = buildMessage({
      text: "older",
      at: "2026-01-01T00:00:00.000Z",
    });
    const raw = JSON.stringify({ [convId]: [known, newer, older] });

    const unseen = readUnseenOutboxEntries(raw);
    expect(unseen[convId]?.map((entry) => entry.localId)).toEqual([
      older.localId,
      newer.localId,
    ]);

    // A second read of the SAME raw now returns nothing new: every id was
    // marked known by the first call.
    expect(readUnseenOutboxEntries(raw)).toEqual({});
  });
});
