import type { MyEvent, Notif } from "./myEvents.types";

// Heavy demo-only My Events registries. Imported *only* via the demo-gated
// dynamic import() in api/useMyEventsData.ts so they code-split out of the
// live bundle (live mode fetches GET /events + GET /event-invites instead).

export const INITIAL_EVENTS: MyEvent[] = [
  {
    id: "bookclub",
    category: "going",
    slug: "stone-butch-blues",
    title: "Queer Book Club — “Stone Butch Blues”",
    date: "2026-06-29",
    start: "19:00",
    end: "21:00",
    venue: "Mouraria Community Centre",
    going: 11,
    reminder: true,
    friends: 3,
    community: "Lisbon Queer Reads",
    access: ["sober", "stepfree"],
    series: {
      label: "Weekly series",
      more: "3 more dates",
      dates: "Tue 7 Jul · Tue 14 Jul · Tue 21 Jul",
    },
    dayof: {
      run: [
        ["18:45", "Doors open · tea & settle in"],
        ["19:00", "Chapter 10 discussion"],
        ["20:30", "Open floor & next pick"],
      ],
      bring: ["Your copy", "Something to sit on"],
      meet: "Mouraria Community Centre — room 2, first floor",
      door: "1942",
    },
    who: [
      ["SR", "jade"],
      ["AK", "coral"],
      ["JP", "plum"],
    ],
    whoText: "Sofia, Anika, Jordan +8 going",
  },
  {
    id: "picnic",
    category: "hosting",
    slug: "trans-joy-picnic",
    title: "Trans Joy Picnic",
    date: "2026-06-30",
    start: "17:30",
    end: "20:30",
    venue: "Jardim da Estrela",
    going: 18,
    waitlist: 4,
    reminder: true,
    community: "Trans Lisbon",
    access: ["stepfree", "quiet", "sober"],
    who: [
      ["NC", "coral"],
      ["KL", "jade"],
      ["MF", "plum"],
    ],
    whoText: "18 going · 4 on the waitlist",
  },
  {
    id: "supper",
    category: "waitlisted",
    slug: "sober-queers-supper",
    title: "Sober Queers Supper Club",
    date: "2026-07-05",
    start: "19:30",
    end: "22:00",
    venue: "A Cevicheria, Príncipe Real",
    going: 20,
    position: 3,
    ahead: 3,
    reminder: true,
    community: "Sober Queers",
    access: ["sober", "stepfree", "content"],
    contentNote: "Content note: open talk about recovery and addiction.",
  },
  {
    id: "karaoke",
    category: "going",
    slug: "queer-karaoke-night",
    maybe: true,
    title: "Queer Karaoke Night",
    date: "2026-07-03",
    start: "21:00",
    end: "23:59",
    venue: "Purex, Bairro Alto",
    going: 28,
    reminder: false,
    friends: 1,
    community: "Nightlife",
    access: ["safer"],
    who: [
      ["DV", "jade"],
      ["BP", "coral"],
    ],
    whoText: "Devon, Beatriz +26 going",
  },
  {
    id: "film",
    category: "going",
    slug: "queer-film-tangerine",
    title: "Queer Film Night — “Tangerine”",
    date: "2026-07-02",
    start: "20:00",
    end: "22:30",
    venue: "Cinema São Jorge",
    going: 24,
    reminder: true,
    friends: 2,
    community: "QueerPulse Cinema",
    access: ["content", "interpret"],
    contentNote: "Content note: brief scenes of transphobic violence.",
    changed: "The host moved this to 20:00 — it was 19:30.",
    paid: "€6",
    ticket: true,
    who: [
      ["TM", "jade"],
      ["BP", "coral"],
      ["JF", "plum"],
    ],
    whoText: "Tomás, Beatriz, Jonas +21 going",
  },
  {
    id: "brunch",
    category: "going",
    slug: "drag-brunch-tia-maria",
    title: "Drag Brunch with Tia Maria",
    date: "2026-07-04",
    start: "12:00",
    end: "15:00",
    venue: "Lux Frágil, Santa Apolónia",
    going: 32,
    reminder: true,
    friends: 5,
    community: "Nightlife",
    access: ["safer", "stepfree"],
    paid: "Pay what you can",
    sliding: true,
    ticket: true,
    who: [
      ["LH", "coral"],
      ["DV", "jade"],
      ["EC", "plum"],
    ],
    whoText: "Laila, Devon, Elena +29 going",
  },
  {
    id: "craft",
    category: "going",
    slug: "queer-craft-market",
    title: "Queer Craft Market",
    date: "2026-07-04",
    start: "14:00",
    end: "16:00",
    venue: "LX Factory, Alcântara",
    going: 40,
    reminder: false,
    blocked: true,
    community: "Makers",
    access: ["stepfree"],
    who: [
      ["MR", "jade"],
      ["TA", "coral"],
    ],
    whoText: "Mar, Téo +38 going",
  },
  {
    id: "workshop",
    category: "going",
    cancelled: true,
    title: "Zine-making Workshop",
    date: "2026-07-07",
    start: "18:30",
    end: "20:30",
    venue: "Casa do Comum",
    going: 0,
    reminder: false,
    community: "Makers",
  },
  {
    id: "aid",
    category: "going",
    slug: "mutual-aid-groceries",
    title: "Mutual Aid Circle — June groceries run",
    date: "2026-07-11",
    start: "11:00",
    end: "13:00",
    venue: "Casa do Comum",
    going: 9,
    reminder: false,
    community: "Mutual Aid Lisbon",
    access: ["stepfree", "masks"],
    who: [
      ["RC", "jade"],
      ["SA", "coral"],
    ],
    whoText: "Rosa, Sofia +7 going",
  },
  {
    id: "poly",
    category: "hosting",
    slug: "poly-open-discussion",
    title: "Poly & Open Relationships Discussion Circle",
    date: "2026-07-18",
    start: "19:00",
    end: "21:00",
    venue: "Online · Zoom",
    online: true,
    timezone: "WEST",
    going: 7,
    waitlist: 0,
    reminder: true,
    community: "Sober Queers",
    access: ["safer"],
    cohost: true,
    cohosts: [["MR", "jade"]],
    cohostName: "Mar R.",
    who: [
      ["IF", "coral"],
      ["TA", "jade"],
      ["KS", "plum"],
    ],
    whoText: "7 going · co-hosted",
  },
  {
    id: "mixer",
    category: "hosting",
    slug: "newcomers-mixer-july",
    review: true,
    title: "Newcomers Mixer — July",
    date: "2026-07-20",
    start: "18:30",
    end: "21:00",
    venue: "A Tasca, Mouraria",
    going: 5,
    waitlist: 0,
    reminder: true,
    community: "Newcomers",
    access: ["stepfree", "sober"],
    who: [["QP", "plum"]],
    whoText: "5 going so far",
  },
  {
    id: "kickoff",
    category: "past",
    title: "Pride Kickoff Mixer",
    date: "2026-06-20",
    start: "19:00",
    end: "23:00",
    venue: "Trumps, Príncipe Real",
    going: 140,
    photos: true,
    taggedPhotos: 4,
    connect: true,
    paid: "€10",
    receipt: true,
    community: "Nightlife",
  },
  {
    id: "sapphic",
    category: "past",
    title: "Sapphic Sundays — slow afternoon",
    date: "2026-06-14",
    start: "16:00",
    end: "19:00",
    venue: "Jardim do Príncipe Real",
    going: 22,
    photos: true,
    connect: true,
    community: "Outdoors",
  },
  {
    id: "potluck",
    category: "past",
    noShow: true,
    title: "Midsummer Potluck",
    date: "2026-06-11",
    start: "19:00",
    end: "22:00",
    venue: "A friend’s rooftop, Graça",
    going: 16,
    community: "Trans Lisbon",
  },
  {
    id: "reading8",
    category: "past",
    title: "Reading Group #8 — “The Dispossessed”",
    date: "2026-06-08",
    start: "19:00",
    end: "21:00",
    venue: "Mouraria Community Centre",
    going: 13,
    photos: false,
    community: "Lisbon Queer Reads",
  },
  {
    id: "quiz",
    category: "past",
    title: "Sapphic Pub Quiz",
    date: "2026-06-02",
    start: "20:00",
    end: "22:30",
    venue: "Damas, Graça",
    going: 30,
    photos: true,
    community: "Nightlife",
  },
  {
    id: "workshop2",
    category: "past",
    title: "Consent & Communication Workshop",
    date: "2026-05-28",
    start: "18:00",
    end: "20:00",
    venue: "Casa do Comum",
    going: 18,
    community: "Sober Queers",
  },
  {
    id: "hike",
    category: "saved",
    title: "Lesbian Hiking Day — Sintra hills",
    date: "2026-07-12",
    start: "09:30",
    end: "16:00",
    venue: "Sintra · meet at Rossio station",
    going: 15,
    spotsLeft: 3,
    access: ["safer"],
    community: "Outdoors",
  },
  {
    id: "ball",
    category: "saved",
    soldOut: true,
    title: "Summer Vogue Ball",
    date: "2026-07-25",
    start: "22:00",
    end: "23:59",
    venue: "Musicbox, Cais do Sodré",
    going: 200,
    paid: "€12",
    access: ["safer"],
    community: "Nightlife",
  },
  {
    id: "comedy",
    category: "invite",
    title: "Queer Comedy Open Mic",
    date: "2026-07-09",
    start: "20:30",
    end: "22:30",
    venue: "Damas, Graça",
    from: "Rita F.",
    going: 19,
    deadline: "Reply by Sun 6 Jul",
    access: ["content", "safer"],
    contentNote: "Content note: comedy may touch on adult themes.",
    paid: "€5",
    community: "Nightlife",
  },
  {
    id: "femmedinner",
    category: "sent",
    title: "Trans Femme Dinner",
    date: "2026-07-15",
    start: "19:30",
    end: "22:00",
    venue: "Your place, Alfama",
    invitee: "Alex M.",
    going: 1,
    community: "Trans Lisbon",
  },
];

export const INITIAL_NOTIFS: Notif[] = [
  {
    id: "n-film",
    bold: "Queer Film Night",
    tail: " moved to 20:00 — it was 19:30.",
    time: "2 hours ago",
    eventId: "film",
    unread: true,
  },
  {
    id: "n-supper",
    lead: "A spot may open soon for ",
    bold: "Sober Queers Supper Club",
    tail: " — you’re #3 in line.",
    time: "Yesterday",
    eventId: "supper",
    unread: true,
  },
  {
    id: "n-comedy",
    bold: "Rita F.",
    tail: " invited you to Queer Comedy Open Mic.",
    time: "Yesterday",
    eventId: "comedy",
    unread: true,
  },
  {
    id: "n-workshop",
    bold: "Zine-making Workshop",
    tail: " was cancelled by the host.",
    time: "Yesterday",
    eventId: "workshop",
    unread: false,
  },
  {
    id: "n-picnic",
    lead: "4 new people joined the waitlist for your ",
    bold: "Trans Joy Picnic",
    tail: ".",
    time: "2 days ago",
    eventId: "picnic",
    unread: false,
  },
  {
    id: "n-brunch",
    lead: "Your RSVP to ",
    bold: "Drag Brunch",
    tail: " is confirmed.",
    time: "3 days ago",
    eventId: "brunch",
    unread: false,
  },
];
