import type { EmailFeatureIcon } from "../emailTemplate.types";

/**
 * Hosted images the email designs use, served from `public/email/` and
 * generated by `scripts/generate-email-assets.mjs`. Files are drawn at 2x;
 * `width` and `height` are the 1x size an email sets on the `<img>`.
 *
 * Emails are pasted into other apps, so every image needs an absolute URL:
 * build it with `emailAssetUrl`.
 */
export interface EmailImageAsset {
  /** Path under the site origin, starting with `/email/`. */
  path: string;
  width: number;
  height: number;
}

export const EMAIL_ASSETS = {
  /** The pulse dot plus "Queer*Pulse*" in cream, for plum grounds. */
  logoOnDark: { path: "/email/logo-on-dark.png", width: 159, height: 32 },
  /** The same lockup in plum with the coral dot, for cream and paper.
   *  A thin white ring round the ink keeps it legible when a dark-mode
   *  client darkens the ground behind it. */
  logoOnLight: { path: "/email/logo-on-light.png", width: 163, height: 32 },
  /** Animated: coral and jade rings pulsing out from the dot on plum-deep. The stage hero's
   *  artwork; the first frame reads on its own for Outlook. */
  heroPulse: { path: "/email/hero-pulse.gif", width: 600, height: 160 },
  /** Animated: a small pulse mark on cream, for the letter design. */
  pulseMark: { path: "/email/pulse-mark.gif", width: 72, height: 72 },
  featureIcons: {
    communities: {
      path: "/email/icon-communities.png",
      width: 48,
      height: 48,
    },
    gatherings: { path: "/email/icon-gatherings.png", width: 48, height: 48 },
    directory: { path: "/email/icon-directory.png", width: 48, height: 48 },
    messages: { path: "/email/icon-messages.png", width: 48, height: 48 },
    magazine: { path: "/email/icon-magazine.png", width: 48, height: 48 },
    safety: { path: "/email/icon-safety.png", width: 48, height: 48 },
  } satisfies Record<EmailFeatureIcon, EmailImageAsset>,
} as const;

export function emailAssetUrl(origin: string, asset: EmailImageAsset): string {
  return `${origin.replace(/\/+$/, "")}${asset.path}`;
}
