import type { ChangemakerDTO } from "../community/api/changemakers.api";

// Illustrative rows for the admin table in demo mode. Mirrors the public
// directory's shape without needing a backend. Static ISO dates only — no
// Date.now() (keeps demo output deterministic).
export const ADMIN_CHANGEMAKERS_DEMO: ChangemakerDTO[] = [
  {
    id: "demo-1",
    slug: "featured-maker",
    name: "Featured Maker",
    initials: "FM",
    cause: "Housing Justice",
    tint: "coral",
    tags: ["Advocacy", "Mutual aid"],
    summary: "A short summary shown on the directory card.",
    imageUrl: null,
    impact: ["Helped 300 people find housing"],
    byline: "By the QueerPulse team",
    heroNote: "Portrait placeholder",
    lead: "Why this changemaker is highlighted.",
    body: ["First paragraph.", "Second paragraph."],
    pullQuoteText: "A representative quote.",
    pullQuoteCite: "Featured Maker",
    status: "published",
    isFeatured: true,
    sortOrder: 0,
    publishedAt: "2026-06-01T00:00:00.000Z",
    createdAt: "2026-06-01T00:00:00.000Z",
    updatedAt: "2026-06-01T00:00:00.000Z",
  },
  {
    id: "demo-2",
    slug: "draft-maker",
    name: "Draft Maker",
    initials: "DM",
    cause: "Climate",
    tint: "jade",
    tags: ["Organizing"],
    summary: "A draft profile not yet visible on the public page.",
    imageUrl: null,
    impact: [],
    byline: "",
    heroNote: "",
    lead: "",
    body: [],
    pullQuoteText: "",
    pullQuoteCite: "",
    status: "draft",
    isFeatured: false,
    sortOrder: 1,
    publishedAt: null,
    createdAt: "2026-06-10T00:00:00.000Z",
    updatedAt: "2026-06-10T00:00:00.000Z",
  },
];
