import type { AuditEntry, LedgerRow, QuarterPoint } from "./adminGovernance.data";

// Heavy demo-only governance mock data (finance ledgers/quarters + audit log).
// Imported *only* via the demo-gated dynamic import()s in
// api/useAdminGovernanceFinances.ts and api/useAdminAudit.ts so it code-splits
// out of the live bundle (live mode calls GET /admin/governance/finances and
// GET /mod/audit instead).

export const LEDGER: LedgerRow[] = [
  {
    labelKey: "governance.ledger.moderatorHonoraria",
    demoLabel: "Moderator honoraria",
    amount: 9600,
    width: 100,
    color: "coral",
  },
  {
    labelKey: "governance.ledger.platformTools",
    demoLabel: "Platform & tools",
    amount: 7200,
    width: 75,
    color: "plum",
  },
  {
    labelKey: "governance.ledger.mutualAid",
    demoLabel: "Mutual aid",
    amount: 6500,
    width: 68,
    color: "jade",
  },
  {
    labelKey: "governance.ledger.mentalHealth",
    demoLabel: "Mental health",
    amount: 3800,
    width: 40,
    color: "violet",
  },
  {
    labelKey: "governance.ledger.magazine",
    demoLabel: "Magazine",
    amount: 2400,
    width: 25,
    color: "amber",
  },
];

export const INCOME_LEDGER: LedgerRow[] = [
  {
    labelKey: "governance.ledger.memberSustainers",
    demoLabel: "Member sustainers",
    amount: 23150,
    width: 67,
    color: "coral",
  },
  {
    labelKey: "governance.ledger.partnerGrants",
    demoLabel: "Partner grants",
    amount: 6400,
    width: 19,
    color: "jade",
  },
  {
    labelKey: "governance.ledger.gatheringTickets",
    demoLabel: "Gathering tickets",
    amount: 4820,
    width: 14,
    color: "violet",
  },
];

export const QUARTERS: QuarterPoint[] = [
  { label: "Q1 25", income: 27.6, spend: 25.8 },
  { label: "Q2 25", income: 29.1, spend: 26.9 },
  { label: "Q3 25", income: 30.4, spend: 27.6 },
  { label: "Q4 25", income: 31.8, spend: 28.4 },
  { label: "Q1 26", income: 33.4, spend: 29.0 },
  { label: "Q2 26", income: 34.37, spend: 29.5 },
];

export const AUDIT_ENTRIES: AuditEntry[] = [
  {
    id: "a1",
    moderatorName: "Júlia Saraiva",
    moderatorInitials: "JS",
    moderatorTone: "jade",
    action: "Removed + banned",
    actionTone: "danger",
    type: "ban",
    subject: "@anon_4471",
    reason:
      "Doxxing: home address shared with a threat. Member offered safety resources.",
    when: "9 min ago",
    range: "today",
  },
  {
    id: "a2",
    moderatorName: "Inês Martins",
    moderatorInitials: "IM",
    moderatorTone: "jade",
    action: "Restricted · 7 days",
    actionTone: "amber",
    type: "restrict",
    subject: "@member·redacted",
    reason: "Repeated DMs after a clear no. Notified with policy excerpt.",
    when: "2 min ago",
    range: "today",
  },
  {
    id: "a3",
    moderatorName: "Júlia Saraiva",
    moderatorInitials: "JS",
    moderatorTone: "jade",
    action: "Dismissed",
    actionTone: "coral",
    type: "dismiss",
    subject: "report #4471",
    reason:
      "Genuine community gathering, not spam. Reporter thanked for caution.",
    when: "1h ago",
    range: "today",
  },
  {
    id: "a4",
    moderatorName: "System",
    moderatorInitials: "SY",
    moderatorTone: "plum",
    action: "Auto-froze account",
    actionTone: "amber",
    type: "suspend",
    subject: "@anon_4471",
    reason:
      "New account, 0 vouches, flagged for doxxing. Held for human review.",
    when: "1h ago",
    range: "today",
  },
  {
    id: "a5",
    moderatorName: "Sofia Almeida",
    moderatorInitials: "SA",
    moderatorTone: "amber",
    action: "Warned",
    actionTone: "coral",
    type: "warn",
    subject: "@coin_daily",
    reason: "First spam offence. Friendly warning + link removed.",
    when: "3h ago",
    range: "today",
  },
  {
    id: "a6",
    moderatorName: "Inês Martins",
    moderatorInitials: "IM",
    moderatorTone: "jade",
    action: "Verified",
    actionTone: "jade",
    type: "shield",
    subject: "Marco Vieira",
    reason: "Two vouches confirmed. Welcomed in.",
    when: "5h ago",
    range: "today",
  },
  {
    id: "a7",
    moderatorName: "Júlia Saraiva",
    moderatorInitials: "JS",
    moderatorTone: "jade",
    action: "Upheld appeal",
    actionTone: "violet",
    type: "appeal_upheld",
    subject: "@dovgrey",
    reason:
      "Context was missed on first review. Restriction lifted, apology sent.",
    when: "yesterday",
    range: "week",
  },
  {
    id: "a8",
    moderatorName: "Kai Sousa",
    moderatorInitials: "KS",
    moderatorTone: "plum",
    action: "Edited policy",
    actionTone: "violet",
    type: "shield",
    subject: "Code of Care v4.2",
    reason: "Added deadnaming clause per Assembly vote.",
    when: "12 Jun",
    range: "quarter",
  },
  {
    id: "a9",
    moderatorName: "Sofia Almeida",
    moderatorInitials: "SA",
    moderatorTone: "amber",
    action: "Restricted · 30 days",
    actionTone: "amber",
    type: "restrict",
    subject: "@p.costa",
    reason:
      "Second misgendering after a warning. Restricted, pointed to the pronoun guide.",
    when: "11 Jun",
    range: "quarter",
  },
  {
    id: "a10",
    moderatorName: "Júlia Saraiva",
    moderatorInitials: "JS",
    moderatorTone: "jade",
    action: "Overturned appeal",
    actionTone: "jade",
    type: "appeal_overturned",
    subject: "@studio.vera",
    reason:
      '"Spam" link was a mutual-aid fund. Warning removed, member thanked.',
    when: "10 Jun",
    range: "quarter",
  },
  {
    id: "a11",
    moderatorName: "Inês Martins",
    moderatorInitials: "IM",
    moderatorTone: "jade",
    action: "Removed content",
    actionTone: "danger",
    type: "remove_content",
    subject: "@throwaway_22",
    reason: "Slur in a public comment. Removed, member warned with the clause.",
    when: "8 Jun",
    range: "quarter",
  },
  {
    id: "a12",
    moderatorName: "System",
    moderatorInitials: "SY",
    moderatorTone: "plum",
    action: "Flagged vouch ring",
    actionTone: "violet",
    type: "escalate",
    subject: "5 accounts",
    reason: "Closed-loop vouching detected. Surfaced for human review.",
    when: "7 Jun",
    range: "quarter",
  },
  {
    id: "a13",
    moderatorName: "Sofia Almeida",
    moderatorInitials: "SA",
    moderatorTone: "amber",
    action: "Verified",
    actionTone: "jade",
    type: "shield",
    subject: "Rui Antunes",
    reason: "Held for a second vouch, then welcomed in once confirmed.",
    when: "5 Jun",
    range: "quarter",
  },
  {
    id: "a14",
    moderatorName: "Júlia Saraiva",
    moderatorInitials: "JS",
    moderatorTone: "jade",
    action: "Dismissed",
    actionTone: "coral",
    type: "dismiss",
    subject: "report #4360",
    reason:
      "Heated but not abusive. No code-of-care breach. Both parties messaged.",
    when: "2 Jun",
    range: "quarter",
  },
  {
    id: "a15",
    moderatorName: "Kai Sousa",
    moderatorInitials: "KS",
    moderatorTone: "plum",
    action: "Warned",
    actionTone: "coral",
    type: "warn",
    subject: "@flats_lx",
    reason: "Repost bot in #housing. Rate-limited and warned.",
    when: "1 Jun",
    range: "quarter",
  },
  {
    id: "a16",
    moderatorName: "Inês Martins",
    moderatorInitials: "IM",
    moderatorTone: "jade",
    action: "Edited policy",
    actionTone: "violet",
    type: "shield",
    subject: "Code of Care v4.1",
    reason: "Extended the appeals window from 7 to 14 days.",
    when: "14 Mar",
    range: "quarter",
  },
];

export const AUDIT_MODERATORS = [
  "Júlia Saraiva",
  "Inês Martins",
  "Sofia Almeida",
  "Kai Sousa",
  "System",
];

