import type { DirectoryPlace } from "./directoryPlaces";

/**
 * Demo-only: queer-owned businesses that live online, with no door to pin.
 *
 * Live mode serves these from the same `GET /directory` feed as every other
 * listing, flagged `online: true` by the listing wizard's "online only"
 * setting. The demo registry had none, which left the directory's Online tab
 * with nothing to show, so these fill it. They join `DIRECTORY_PLACES` at its
 * tail, so the curated order of the physical places is untouched.
 *
 * Every field an online listing leaves empty in the wizard (address, hours,
 * coordinates, neighbourhood) is left empty here too, so demo exercises the
 * same "nothing to show" paths a real online listing does.
 */
export const ONLINE_DIRECTORY_PLACES: DirectoryPlace[] = [
  {
    slug: "fio-solto",
    name: "Fio Solto",
    cat: "culture",
    hood: "",
    owned: true,
    queerOwnedVerified: true,
    ownedBy: ["nonbinary"],
    av: "FS",
    tint: "coral",
    desc: "A risograph zine shop run from a spare room. Queer comics, poetry and Portuguese-language small press, posted anywhere in Portugal.",
    tagline:
      "Small-press queer zines, printed by hand and posted to your door.",
    pills: ["Zines & small press", "Ships across Portugal", "€"],
    rating: { score: "4.9", count: 31 },
    gallery: [
      "Riso drum, mid-print",
      "Zine wall",
      "Packing table",
      "Stack of first editions",
    ],
    whatItIs: [
      "Fio Solto is a one-person zine shop and riso press. Everything in the catalogue is made by queer artists, most of them working in Portuguese, many of them printing for the first time.",
      "Orders are packed by hand twice a week. If you make zines yourself, there is a standing open call: send a PDF and a note, and every submission gets a reply.",
    ],
    goodFor: [
      { label: "Queer comics in Portuguese", yes: true },
      { label: "A gift that someone actually made", yes: true },
      { label: "First-time zine makers", yes: true },
      { label: "Same-day delivery", yes: false },
    ],
    hoursType: "appointment",
    hoursNote:
      "Orders packed Tuesdays and Fridays. Messages answered within a day.",
    owner: {
      name: "Sam Ferreira",
      initials: "SF",
      tint: "coral",
      role: "Founder · printer",
      bio: "Prints other people's zines more than their own. Will talk about riso ink for hours.",
      inQueerPulse: true,
      first: "Sam",
    },
    social: {
      instagram: "@fiosolto.zines",
      website: "fiosolto.pt",
      email: "ola@fiosolto.pt",
    },
    address: "",
    online: true,
    reviews: [
      {
        id: "fio-solto-review-1",
        initials: "MR",
        name: "Marta R.",
        tint: "jade",
        byline: "she/her · reader",
        stars: 5,
        text: "Ordered three zines and got a handwritten note with each. The trans poetry anthology made me cry on the 28.",
        helpful: 9,
      },
    ],
  },
  {
    slug: "corpo-inteiro-terapia",
    name: "Corpo Inteiro",
    cat: "health",
    hood: "",
    owned: true,
    queerOwnedVerified: true,
    ownedBy: ["trans"],
    av: "CI",
    tint: "jade",
    desc: "Queer and trans-affirming therapy by video, in Portuguese and English. Sliding-scale places held every month for newcomers.",
    tagline: "Therapy where you don't have to explain yourself first.",
    pills: ["Therapy", "PT & EN", "Sliding scale", "€€"],
    rating: { score: "5.0", count: 18 },
    gallery: [
      "Consulting room, on screen",
      "Reading corner",
      "Window light",
      "Notebook and tea",
    ],
    whatItIs: [
      "Corpo Inteiro is a small online practice of two psychologists, both registered with the Ordem, both queer, one of them trans. Sessions run by video, so it works from Porto, the Algarve, or a flat share in Arroios.",
      "A handful of sliding-scale places open every month, prioritised for people who have just arrived in Portugal or are mid-transition and waiting on the public system.",
    ],
    goodFor: [
      { label: "Gender-affirming support", yes: true },
      { label: "Newcomers to Portugal", yes: true },
      { label: "Couples & polycules", yes: true },
      { label: "Crisis or emergency care", yes: false },
    ],
    hoursType: "appointment",
    hoursNote: "Sessions by appointment, weekdays and two evenings a week.",
    owner: {
      name: "Rafa Lopes",
      initials: "RL",
      tint: "jade",
      role: "Psychologist · co-founder",
      bio: "Trans psychologist. Started the practice after waiting eleven months for an appointment of their own.",
      inQueerPulse: true,
      first: "Rafa",
    },
    social: {
      website: "corpointeiro.pt",
      email: "consultas@corpointeiro.pt",
    },
    address: "",
    online: true,
    reviews: [
      {
        id: "corpo-inteiro-terapia-review-1",
        initials: "JT",
        name: "Jo T.",
        tint: "plum",
        byline: "they/them · client",
        stars: 5,
        text: "First therapist I didn't have to give a gender studies lecture to. The sliding scale is real, and nobody made me justify it.",
        helpful: 14,
      },
    ],
  },
  {
    slug: "peito-livre",
    name: "Peito Livre",
    cat: "design",
    hood: "",
    owned: true,
    ownedBy: ["trans", "nonbinary"],
    av: "PL",
    tint: "plum",
    desc: "Binders, tucking wear and swimwear designed and sewn in Portugal, in sizes that start where the big brands stop.",
    tagline:
      "Gender-affirming clothes, cut for real bodies and sewn close to home.",
    pills: [
      "Gender-affirming wear",
      "Made in Portugal",
      "Discreet packaging",
      "€€",
    ],
    rating: { score: "4.8", count: 57 },
    gallery: [
      "Cutting table",
      "Swimwear range",
      "Fit guide",
      "Discreet parcel",
    ],
    whatItIs: [
      "Peito Livre designs binders, tucking underwear and swimwear, and has them sewn by a family workshop in Guimarães. The size range runs well past where imported brands give up.",
      "Every parcel ships in plain packaging with a neutral sender name, and the fit team answers questions by message, so nobody has to guess their size alone.",
    ],
    goodFor: [
      { label: "A first binder", yes: true },
      { label: "Plus sizes", yes: true },
      { label: "Discreet delivery", yes: true },
      { label: "Trying on in person", yes: false },
    ],
    hoursType: "shop",
    hoursNote:
      "Orders ship within two working days. Fit questions answered by message.",
    owner: {
      name: "Alex & Noa",
      initials: "PL",
      tint: "plum",
      role: "Co-founders",
      bio: "A trans man and a non-binary seamstress who got tired of binders that didn't fit and swimwear that didn't exist.",
      inQueerPulse: true,
      first: "Alex",
    },
    social: {
      instagram: "@peitolivre",
      website: "peitolivre.pt",
      email: "ajuda@peitolivre.pt",
    },
    address: "",
    online: true,
    reviews: [
      {
        id: "peito-livre-review-1",
        initials: "DV",
        name: "Duarte V.",
        tint: "coral",
        byline: "he/him · customer",
        stars: 5,
        text: "Messaged them my measurements, got a size recommendation in an hour, and the binder fits like it was made for me. Because it sort of was.",
        helpful: 22,
      },
    ],
  },
  {
    slug: "codigo-arco",
    name: "Código Arco",
    cat: "tech",
    hood: "",
    owned: true,
    queerOwnedVerified: true,
    ownedBy: ["women"],
    av: "CA",
    tint: "jade",
    desc: "A remote web studio building accessible, bilingual sites for queer collectives, NGOs and the small businesses in this directory.",
    tagline: "Websites that work for everyone, built by people who get it.",
    pills: ["Web studio", "Accessibility audits", "Bilingual PT/EN", "€€"],
    rating: { score: "4.9", count: 12 },
    gallery: [
      "Wireframes on the wall",
      "Screen reader test",
      "Design system",
      "Launch day",
    ],
    whatItIs: [
      "Código Arco is three developers and a designer, working remotely from Lisbon, Porto and Coimbra. They build sites for collectives, associations and queer-owned businesses, with accessibility treated as part of the job, not an upsell.",
      "Collectives with no budget can apply for one pro-bono build a quarter. Everything else is quoted up front, in plain language.",
    ],
    goodFor: [
      { label: "A site for a collective", yes: true },
      { label: "Accessibility audits", yes: true },
      { label: "Bilingual PT/EN content", yes: true },
      { label: "Crypto or ad-tech projects", yes: false },
    ],
    hoursType: "appointment",
    hoursNote: "Calls by appointment, Monday to Thursday.",
    owner: {
      name: "Helena Matos",
      initials: "HM",
      tint: "jade",
      role: "Founder · developer",
      bio: "Builds websites that screen readers can actually use. Ran the tech for two Lisbon Prides.",
      inQueerPulse: true,
      first: "Helena",
    },
    social: {
      website: "codigoarco.pt",
      email: "projetos@codigoarco.pt",
    },
    address: "",
    online: true,
    reviews: [
      {
        id: "codigo-arco-review-1",
        initials: "CQ",
        name: "Coletivo Quarto",
        tint: "plum",
        byline: "collective · client",
        stars: 5,
        text: "They rebuilt our site for free through the pro-bono round and it's the first one our blind members could use on their own.",
        helpful: 11,
      },
    ],
  },
  {
    slug: "molho-bravo",
    name: "Molho Bravo",
    cat: "food",
    hood: "",
    owned: true,
    av: "MB",
    tint: "coral",
    desc: "Small-batch piri-piri and fermented hot sauces, bottled in a shared kitchen and posted across Portugal and the EU.",
    tagline: "Hot sauce with a grudge and a family recipe.",
    pills: ["Hot sauce", "Ships to the EU", "Vegan", "€"],
    rating: { score: "4.7", count: 44 },
    gallery: [
      "Chillies drying",
      "Fermentation jars",
      "Labelling day",
      "The full range",
    ],
    whatItIs: [
      "Molho Bravo started as a grandmother's piri-piri recipe and a queer kitchen's refusal to keep it to themselves. It now runs to six sauces, all fermented for at least a month, all vegan.",
      "Bottled in a shared kitchen in Marvila and posted twice a week. A cut of every bottle goes to a Lisbon queer food bank.",
    ],
    goodFor: [
      { label: "Gifts that travel well", yes: true },
      { label: "Vegan kitchens", yes: true },
      { label: "Supporting a food bank", yes: true },
      { label: "People who can't take heat", yes: false },
    ],
    hoursType: "shop",
    hoursNote: "Orders posted Mondays and Thursdays.",
    owner: {
      name: "André Sousa",
      initials: "AS",
      tint: "coral",
      role: "Founder · cook",
      bio: "Ferments things. Runs the hot sauce, a supper club, and his grandmother's legacy, in roughly that order.",
      inQueerPulse: true,
      first: "André",
    },
    social: {
      instagram: "@molhobravo",
      website: "molhobravo.pt",
    },
    address: "",
    online: true,
    reviews: [
      {
        id: "molho-bravo-review-1",
        initials: "IN",
        name: "Ivo N.",
        tint: "jade",
        byline: "he/him · customer",
        stars: 4,
        text: "The fermented one is ridiculous on eggs. Only docking a star because the 'medium' is a lie, in the best way.",
        helpful: 6,
      },
    ],
  },
  {
    slug: "aulas-kiki",
    name: "Aulas Kiki",
    cat: "culture",
    hood: "",
    owned: true,
    queerOwnedVerified: true,
    ownedBy: ["women", "trans"],
    av: "AK",
    tint: "plum",
    desc: "Portuguese lessons by video for queer newcomers, with vocabulary the textbooks leave out: the SNS, the AIMA queue and a night out.",
    tagline: "Portuguese for the life you actually live here.",
    pills: ["Language lessons", "Small groups", "A1 to B2", "€"],
    rating: { score: "4.9", count: 39 },
    gallery: [
      "Group class on screen",
      "Flashcards",
      "Conversation night",
      "Lesson notes",
    ],
    whatItIs: [
      "Aulas Kiki teaches European Portuguese online, in small groups of queer and trans newcomers. Lessons cover the things you need first: talking to a GP, filling in forms with the right pronouns, and holding your own at a bar.",
      "Groups cap at six. A monthly free conversation night is open to anyone, whatever their level.",
    ],
    goodFor: [
      { label: "Newcomers to Lisbon", yes: true },
      { label: "Learning with people like you", yes: true },
      { label: "Exam preparation", yes: true },
      { label: "Brazilian Portuguese", yes: false },
    ],
    hoursType: "appointment",
    hoursNote:
      "Group classes on weekday evenings. Private lessons by appointment.",
    owner: {
      name: "Beatriz Nunes",
      initials: "BN",
      tint: "plum",
      role: "Teacher · founder",
      bio: "Trans woman, language teacher, former newcomer herself (to Lisbon, from Viseu). Patient with verbs and people.",
      inQueerPulse: true,
      first: "Beatriz",
    },
    social: {
      instagram: "@aulaskiki",
      website: "aulaskiki.pt",
      email: "ola@aulaskiki.pt",
    },
    address: "",
    online: true,
    reviews: [
      {
        id: "aulas-kiki-review-1",
        initials: "LK",
        name: "Lee K.",
        tint: "coral",
        byline: "she/they · student",
        stars: 5,
        text: "Three months in and I booked my own doctor's appointment in Portuguese. Beatriz made the grammar feel survivable.",
        helpful: 17,
      },
    ],
  },
];
