import type { IconType } from "react-icons";
import {
  FiMusic,
  FiCoffee,
  FiPlusCircle,
  FiBookOpen,
  FiDroplet,
  FiUsers,
  FiScissors,
  FiActivity,
  FiPenTool,
  FiCpu,
} from "react-icons/fi";
import {
  FaWineGlass,
  FaMartiniGlass,
  FaUtensils,
  FaHeartPulse,
  FaPeopleGroup,
  FaMasksTheater,
  FaDumbbell,
} from "react-icons/fa6";

export interface Venue {
  id: string;
  name: string;
  bairro: string; // informal area, kept for the card subtitle only
  freguesia: string; // official parish — the map + filter key
  latitude: number;
  longitude: number;
  type: string;
  vibe: string[];
  accessible: boolean;
  address: string;
  hours: string;
  note: string;
  beenHere: number;
}

export const VENUES: Venue[] = [
  {
    id: "v1",
    name: "Finalmente",
    bairro: "Príncipe Real",
    freguesia: "Misericórdia",
    latitude: 38.7168,
    longitude: -9.1489,
    type: "bar",
    vibe: ["mixed", "masc-leaning"],
    accessible: true,
    address: "Rua da Palmeira 38",
    hours: "11pm – 6am",
    note: "The longest-running queer bar in Lisbon. Come for the drag shows on weekends — they are unmissable.",
    beenHere: 247,
  },
  {
    id: "v2",
    name: "Trumps",
    bairro: "Príncipe Real",
    freguesia: "Misericórdia",
    latitude: 38.7163,
    longitude: -9.1478,
    type: "club",
    vibe: ["mixed"],
    accessible: false,
    address: "Rua da Imprensa Nacional 104B",
    hours: "Thu–Sat 11pm – 6am",
    note: "The closest thing Lisbon has to a legendary queer institution. Three rooms, one very good time.",
    beenHere: 189,
  },
  {
    id: "v3",
    name: "Bar 106",
    bairro: "Príncipe Real",
    freguesia: "Misericórdia",
    latitude: 38.717,
    longitude: -9.1477,
    type: "bar",
    vibe: ["mixed", "masc-leaning"],
    accessible: true,
    address: "Rua de São Marçal 106",
    hours: "9pm – 2am",
    note: "Low-key and brilliant. The best place to start a Príncipe Real evening before it gets loud.",
    beenHere: 134,
  },
  {
    id: "v4",
    name: "Hot Clube de Portugal",
    bairro: "Príncipe Real",
    freguesia: "Misericórdia",
    latitude: 38.7161,
    longitude: -9.1488,
    type: "café",
    vibe: ["mixed", "sober-friendly"],
    accessible: false,
    address: "Praça da Alegria 48",
    hours: "Tue–Sat 10pm – 2am",
    note: "Historic jazz club, wholly queer-welcoming and entirely its own thing.",
    beenHere: 71,
  },
  {
    id: "v5",
    name: "Ler Devagar",
    bairro: "LX Factory",
    freguesia: "Alcântara",
    latitude: 38.7037,
    longitude: -9.1787,
    type: "bookshop",
    vibe: ["mixed"],
    accessible: true,
    address: "Rua Rodrigues de Faria 103",
    hours: "Mon–Fri 11am – 8pm · weekends 10am – 9pm",
    note: "The most beautiful bookshop in Lisbon. Not exclusively queer but completely welcoming.",
    beenHere: 156,
  },
  {
    id: "v6",
    name: "GAT Lisboa",
    bairro: "Mouraria",
    freguesia: "Santa Maria Maior",
    latitude: 38.716,
    longitude: -9.1346,
    type: "clinic",
    vibe: ["mixed", "trans-centred"],
    accessible: true,
    address: "Rua de São Lázaro 58",
    hours: "Mon–Fri 9am – 5pm",
    note: "Free HIV and STI testing, trans health support, harm reduction. No judgment, no referral needed.",
    beenHere: 78,
  },
  {
    id: "v7",
    name: "Tasca do Chico",
    bairro: "Mouraria",
    freguesia: "Santa Maria Maior",
    latitude: 38.7151,
    longitude: -9.1344,
    type: "café",
    vibe: ["mixed", "sober-friendly"],
    accessible: false,
    address: "Rua do Diário de Notícias 39",
    hours: "Mon–Sat 7pm – midnight",
    note: "Fado and petiscos. Not queer-specific but genuinely feels like home.",
    beenHere: 203,
  },
  {
    id: "v8",
    name: "Casa Qui",
    bairro: "Mouraria",
    freguesia: "Santa Maria Maior",
    latitude: 38.7159,
    longitude: -9.1355,
    type: "community space",
    vibe: ["mixed", "trans-centred", "femme-leaning"],
    accessible: true,
    address: "Largo do Intendente 27",
    hours: "Tue–Sat 11am – 7pm",
    note: "Queer community centre with events, legal support, and a library. Always something on.",
    beenHere: 88,
  },
  {
    id: "v9",
    name: "ILGA Portugal",
    bairro: "Intendente",
    freguesia: "Arroios",
    latitude: 38.722,
    longitude: -9.1351,
    type: "community space",
    vibe: ["mixed", "trans-centred"],
    accessible: true,
    address: "Rua dos Fanqueiros 38",
    hours: "Mon–Fri 10am – 6pm",
    note: "The main LGBTQ+ organisation in Portugal. Legal support, mental health, community programmes.",
    beenHere: 112,
  },
  {
    id: "v10",
    name: "Purex",
    bairro: "Intendente",
    freguesia: "Arroios",
    latitude: 38.7211,
    longitude: -9.1349,
    type: "club",
    vibe: ["mixed", "femme-leaning"],
    accessible: false,
    address: "Rua das Salgadeiras 28",
    hours: "Fri–Sat midnight – 6am",
    note: "One of the most genuinely queer clubs in Lisbon. Eclectic music, no attitude.",
    beenHere: 143,
  },
  {
    id: "v11",
    name: "Opus Gay",
    bairro: "Bairro Alto",
    freguesia: "Misericórdia",
    latitude: 38.7133,
    longitude: -9.1456,
    type: "bar",
    vibe: ["mixed", "masc-leaning"],
    accessible: true,
    address: "Rua da Atalaia 34",
    hours: "Mon–Sat 10pm – 4am",
    note: "Relaxed bar with a good terrace. Solid middle ground between loud and quiet.",
    beenHere: 119,
  },
  {
    id: "v12",
    name: "Shelter",
    bairro: "Bairro Alto",
    freguesia: "Misericórdia",
    latitude: 38.7124,
    longitude: -9.1454,
    type: "club",
    vibe: ["masc-leaning"],
    accessible: false,
    address: "Rua da Barroca 33",
    hours: "Fri–Sat 11pm – 6am",
    note: "Cruisy, dark, electronic. Knows exactly what it is.",
    beenHere: 98,
  },
  {
    id: "v13",
    name: "Checkpoint",
    bairro: "Cais do Sodré",
    freguesia: "Misericórdia",
    latitude: 38.7073,
    longitude: -9.1454,
    type: "clinic",
    vibe: ["mixed", "masc-leaning"],
    accessible: true,
    address: "Rua do Crucifixo 100",
    hours: "Mon–Fri 1pm – 8pm",
    note: "Community-led HIV/STI testing and PrEP support. Walk-ins welcome.",
    beenHere: 67,
  },
  {
    id: "v14",
    name: "Sauna Saturno",
    bairro: "Santos",
    freguesia: "Estrela",
    latitude: 38.708,
    longitude: -9.1584,
    type: "sauna",
    vibe: ["masc-leaning"],
    accessible: true,
    address: "Rua de Santos-o-Velho 14",
    hours: "Daily 2pm – midnight",
    note: "Clean, friendly, no pressure. Trans men welcome. Towel and locker included.",
    beenHere: 54,
  },
  {
    id: "v15",
    name: "A Cevicheria",
    bairro: "Príncipe Real",
    freguesia: "Misericórdia",
    latitude: 38.7172,
    longitude: -9.1481,
    type: "café",
    vibe: ["mixed", "sober-friendly"],
    accessible: true,
    address: "Rua Dom Pedro V 129",
    hours: "Mon–Sat 12pm – midnight",
    note: "Not queer-specific but one of the most welcoming spots in Príncipe Real. Great natural wine list.",
    beenHere: 165,
  },
  {
    id: "v16",
    name: "Navalha",
    bairro: "Príncipe Real",
    freguesia: "Misericórdia",
    latitude: 38.716,
    longitude: -9.1485,
    type: "barbershop",
    vibe: ["mixed", "masc-leaning", "trans-centred"],
    accessible: true,
    address: "Rua da Escola Politécnica 62",
    hours: "Tue–Sat 10am – 7pm",
    note: "Queer-owned barbershop with real expertise in trans haircuts. No awkward questions, no gendered pricing.",
    beenHere: 184,
  },
  {
    id: "v17",
    name: "Salão Mouraria",
    bairro: "Mouraria",
    freguesia: "Santa Maria Maior",
    latitude: 38.7149,
    longitude: -9.1354,
    type: "barbershop",
    vibe: ["mixed", "femme-leaning"],
    accessible: false,
    address: "Rua do Capelão 22",
    hours: "Mon–Sat 9am – 6pm",
    note: "Neighbourhood salon that became a queer anchor without fuss. Bilingual, trans-welcoming, affordable.",
    beenHere: 97,
  },
  {
    id: "v18",
    name: "Studio Cabelo",
    bairro: "Intendente",
    freguesia: "Arroios",
    latitude: 38.7219,
    longitude: -9.136,
    type: "barbershop",
    vibe: ["mixed"],
    accessible: true,
    address: "Largo do Intendente 4",
    hours: "Tue–Sat 11am – 8pm",
    note: "Gender-neutral pricing across the board. They will not charge you more because of your hair length.",
    beenHere: 122,
  },
  {
    id: "v19",
    name: "A Tesoura",
    bairro: "Santos",
    freguesia: "Estrela",
    latitude: 38.707,
    longitude: -9.1576,
    type: "barbershop",
    vibe: ["femme-leaning", "mixed"],
    accessible: false,
    address: "Rua de Santos-o-Velho 8",
    hours: "Wed–Sun 10am – 6pm",
    note: "Small queer-run salon. Specialises in curly and natural hair. Known in the trans femme community for getting it right.",
    beenHere: 76,
  },
  {
    id: "v20",
    name: "Academia Livre",
    bairro: "Cais do Sodré",
    freguesia: "Misericórdia",
    latitude: 38.7063,
    longitude: -9.1446,
    type: "gym",
    vibe: ["mixed", "trans-centred"],
    accessible: true,
    address: "Rua do Alecrim 44",
    hours: "Mon–Fri 7am – 10pm · Sat–Sun 9am – 6pm",
    note: "The most trans-inclusive gym in the city. Gender-neutral changing rooms on every floor, pronoun lanyards at reception.",
    beenHere: 143,
  },
  {
    id: "v21",
    name: "Corpo Livre",
    bairro: "Bairro Alto",
    freguesia: "Misericórdia",
    latitude: 38.7132,
    longitude: -9.1466,
    type: "gym",
    vibe: ["mixed", "femme-leaning"],
    accessible: false,
    address: "Rua Nova do Carvalho 18",
    hours: "Mon–Fri 8am – 9pm · Sat 9am – 5pm",
    note: "Feminist and queer-centred fitness space. Small classes, no mirrors, no weight scales. Body-neutral by design.",
    beenHere: 88,
  },
  {
    id: "v22",
    name: "Clube Intendente",
    bairro: "Intendente",
    freguesia: "Arroios",
    latitude: 38.7209,
    longitude: -9.1359,
    type: "gym",
    vibe: ["mixed"],
    accessible: true,
    address: "Rua do Benformoso 191",
    hours: "Mon–Sat 7am – 10pm",
    note: "Community gym with a genuinely welcoming culture. Queer swim sessions on Thursdays 7–9pm.",
    beenHere: 61,
  },
  {
    id: "v23",
    name: "Movimento",
    bairro: "Alfama",
    freguesia: "Santa Maria Maior",
    latitude: 38.7114,
    longitude: -9.1285,
    type: "gym",
    vibe: ["mixed", "masc-leaning"],
    accessible: true,
    address: "Rua dos Remedios 52",
    hours: "Daily 8am – 10pm",
    note: "Yoga, capoeira, and weights in a converted warehouse. Queer-run, sliding-scale memberships available.",
    beenHere: 54,
  },
];

// `t` is the canonical (English, stored/filter) type id — never translate the
// id itself, only `labelKey`'s resolved value (i18n brief §5.1: enum/filter
// values must stay stable across a language switch).
export const TYPES = [
  { t: "all", labelKey: "marketing:map.filter.type.all" },
  { t: "bar", labelKey: "marketing:map.filter.type.bar" },
  { t: "club", labelKey: "marketing:map.filter.type.club" },
  { t: "café", labelKey: "marketing:map.filter.type.cafe" },
  { t: "clinic", labelKey: "marketing:map.filter.type.clinic" },
  { t: "bookshop", labelKey: "marketing:map.filter.type.bookshop" },
  { t: "sauna", labelKey: "marketing:map.filter.type.sauna" },
  {
    t: "community space",
    labelKey: "marketing:map.filter.type.communitySpace",
  },
  { t: "barbershop", labelKey: "marketing:map.filter.type.barbershop" },
  { t: "gym", labelKey: "marketing:map.filter.type.gym" },
];
/** Canonical (English, stored) vibe ids — same stored-value rule as `TYPES`. */
export const VIBES = [
  "mixed",
  "masc-leaning",
  "femme-leaning",
  "trans-centred",
  "sober-friendly",
];
/** Display label key for each canonical vibe id. */
export const VIBE_LABEL_KEYS: Record<string, string> = {
  mixed: "marketing:map.filter.vibe.mixed",
  "masc-leaning": "marketing:map.filter.vibe.mascLeaning",
  "femme-leaning": "marketing:map.filter.vibe.femmeLeaning",
  "trans-centred": "marketing:map.filter.vibe.transCentred",
  "sober-friendly": "marketing:map.filter.vibe.soberFriendly",
};
/** Display label key for each canonical venue-type id (mirrors `TYPES`, minus "all"). */
export const TYPE_LABEL_KEYS: Record<string, string> = Object.fromEntries(
  TYPES.filter((type) => type.t !== "all").map((type) => [
    type.t,
    type.labelKey,
  ]),
);

export const TYPE_BG: Record<string, string> = {
  bar: "rgba(232,119,90,.14)",
  club: "rgba(45,27,61,.1)",
  café: "rgba(74,140,111,.12)",
  clinic: "rgba(74,140,111,.14)",
  bookshop: "rgba(232,119,90,.1)",
  sauna: "rgba(45,27,61,.08)",
  "community space": "rgba(74,140,111,.14)",
  barbershop: "rgba(185,130,80,.15)",
  gym: "rgba(80,120,185,.13)",
};
export const TYPE_FG: Record<string, string> = {
  bar: "var(--accent-ink)",
  club: "var(--plum)",
  café: "var(--jade)",
  clinic: "var(--jade)",
  bookshop: "var(--accent-ink)",
  sauna: "var(--ink-60)",
  "community space": "var(--jade)",
  barbershop: "#9A6820",
  gym: "#3A5EA0",
};
export const TYPE_ICON: Record<string, IconType> = {
  bar: FaWineGlass,
  club: FiMusic,
  café: FiCoffee,
  clinic: FiPlusCircle,
  bookshop: FiBookOpen,
  sauna: FiDroplet,
  "community space": FiUsers,
  barbershop: FiScissors,
  gym: FiActivity,
};
/** Icon per unified category — every Local map pin + filter chip keys off this.
 *  Distinct, evocative glyphs (no duplicates) so each category reads at pin size. */
export const CATEGORY_ICON: Record<string, IconType> = {
  nightlife: FaMartiniGlass,
  food: FaUtensils,
  health: FaHeartPulse,
  space: FaPeopleGroup,
  culture: FaMasksTheater,
  design: FiPenTool,
  tech: FiCpu,
  grooming: FiScissors,
  fitness: FaDumbbell,
};
/** Fill colour per unified category — the CSS var mirrors these (--cat-*),
 *  driven by `data-category` on pins + chips. Kept here as the JS-side legend
 *  source (e.g. tests / any inline need). Values match tokens/colors.css. */
export const CATEGORY_COLOR: Record<string, string> = {
  nightlife: "var(--cat-nightlife)",
  food: "var(--cat-food)",
  health: "var(--cat-health)",
  space: "var(--cat-space)",
  culture: "var(--cat-culture)",
  design: "var(--cat-design)",
  tech: "var(--cat-tech)",
  grooming: "var(--cat-grooming)",
  fitness: "var(--cat-fitness)",
};
export const VIBE_BG: Record<string, string> = {
  mixed: "rgba(45,27,61,.06)",
  "masc-leaning": "rgba(45,27,61,.09)",
  "femme-leaning": "rgba(232,119,90,.09)",
  "trans-centred": "rgba(74,140,111,.1)",
  "sober-friendly": "rgba(74,140,111,.08)",
};
export const VIBE_FG: Record<string, string> = {
  mixed: "var(--ink-60)",
  "masc-leaning": "var(--ink-60)",
  "femme-leaning": "var(--accent-ink)",
  "trans-centred": "var(--jade)",
  "sober-friendly": "var(--jade)",
};
