import type { TFunction } from "../../shared/i18n/types";

/**
 * The press kit's downloadable brand assets.
 *
 * These are REAL files, committed to `public/press/` and served as static
 * assets — not blobs synthesised in the browser. They are generated by
 * `scripts/generate-press-assets.mjs` from the app's own sources: the mark
 * is drawn from `brandMark.geometry.json` (the same geometry the BrandMark
 * component and the PWA icons use), the wordmark is rendered in the app's
 * self-hosted Fraunces, and every
 * published colour and type value is read out of `src/styles/tokens/`. Re-run
 * `pnpm press:assets` when the mark, palette or type tokens change.
 *
 * Anything the platform does not actually have (a photography pack, a printed
 * fact sheet) has no entry here and no card on the page: an asset either exists
 * as a file a journalist can open, or it is not offered.
 */

/** Where the generated assets are served from. */
const PRESS_ASSET_BASE = "/press";

export interface PressAsset {
  /** Same-origin path to the real file. The browser fetches it directly, so
   *  the host supplies the MIME type. */
  path: string;
  /** The name the file is saved under, via the anchor's `download`. */
  filename: string;
  /** Short format label shown on the download card and preview rows. */
  format: string;
}

function pressAsset(filename: string, format: string): PressAsset {
  return { path: `${PRESS_ASSET_BASE}/${filename}`, filename, format };
}

export const PRESS_ASSETS = {
  /** Everything below, plus a README and the licence, in one archive. */
  completeKit: pressAsset("queerpulse-press-kit.zip", "ZIP"),
  /** The mark, full colour, vector. */
  markSvg: pressAsset("queerpulse-mark.svg", "SVG"),
  /** The mark as a single-colour silhouette, vector. */
  markMonochromeSvg: pressAsset("queerpulse-mark-monochrome.svg", "SVG"),
  /** Wordmark for light grounds: plum ink, coral pulse dot, transparent. */
  logoPrimary: pressAsset("queerpulse-logo-primary.png", "PNG"),
  /** Wordmark for dark grounds: cream ink, coral pulse dot, transparent. */
  logoInverse: pressAsset("queerpulse-logo-inverse.png", "PNG"),
  /** Wordmark on the coral field: cream ink, plum pulse dot. */
  logoCoral: pressAsset("queerpulse-logo-coral.png", "PNG"),
  /** The app icon exactly as it ships on devices. */
  appIcon: pressAsset("queerpulse-app-icon-512.png", "PNG"),
  /** Printable colour + typography reference, generated from the tokens. */
  brandReference: pressAsset("queerpulse-brand-reference.pdf", "PDF"),
} as const;

/** The contents of the complete-kit archive, listed in its download modal. */
export function buildKitPreview(
  t: TFunction,
): { format: string; title: string; description: string }[] {
  return [
    {
      format: "TXT",
      title: t("marketing:pressKit.preview.readme.title"),
      description: t("marketing:pressKit.preview.readme.desc"),
    },
    {
      format: "SVG",
      title: t("marketing:pressKit.preview.marks.title"),
      description: t("marketing:pressKit.preview.marks.desc"),
    },
    {
      format: "PNG",
      title: t("marketing:pressKit.preview.marksPng.title"),
      description: t("marketing:pressKit.preview.marksPng.desc"),
    },
    {
      format: "PNG",
      title: t("marketing:pressKit.preview.appIcon.title"),
      description: t("marketing:pressKit.preview.appIcon.desc"),
    },
    {
      format: "PDF",
      title: t("marketing:pressKit.preview.brandReference.title"),
      description: t("marketing:pressKit.preview.brandReference.desc"),
    },
    {
      format: "TXT",
      title: t("marketing:pressKit.preview.colour.title"),
      description: t("marketing:pressKit.preview.colour.desc"),
    },
  ];
}
