import type { StickerPackResponse } from "../../shared/contracts/contracts";

/**
 * The demo catalogue. GENERATED by `scripts/generate-sticker-packs.mjs`
 * (`pnpm stickers`); edit the generator, never this file.
 *
 * One pack: the Uno reverse card template, painted for every flag in
 * `UNO_REVERSE_FLAG_IDS`. The PNGs it points at live alongside it under
 * `public/stickers/uno-reverse/`, written by the same generator run.
 */
export const DEMO_STICKER_PACKS: StickerPackResponse[] = [
  {
    id: "demo-sticker-pack-uno-reverse",
    slug: "uno-reverse",
    name: "Uno reverse",
    description: "Every striped pride flag, drawn as an Uno reverse card.",
    coverStickerId: "demo-sticker-uno-reverse-rainbow",
    stickers: [
      {
        id: "demo-sticker-uno-reverse-rainbow",
        slug: "uno-reverse-rainbow",
        label: "Rainbow reverse",
        url: "/stickers/uno-reverse/rainbow.png",
        width: 512,
        height: 512,
        keywords: {
          en: ["rainbow", "uno", "reverse"],
          pt: ["rainbow", "uno", "reverso"],
        },
      },
      {
        id: "demo-sticker-uno-reverse-transgender",
        slug: "uno-reverse-transgender",
        label: "Transgender reverse",
        url: "/stickers/uno-reverse/transgender.png",
        width: 512,
        height: 512,
        keywords: {
          en: ["transgender", "uno", "reverse"],
          pt: ["transgender", "uno", "reverso"],
        },
      },
      {
        id: "demo-sticker-uno-reverse-bisexual",
        slug: "uno-reverse-bisexual",
        label: "Bisexual reverse",
        url: "/stickers/uno-reverse/bisexual.png",
        width: 512,
        height: 512,
        keywords: {
          en: ["bisexual", "uno", "reverse"],
          pt: ["bisexual", "uno", "reverso"],
        },
      },
      {
        id: "demo-sticker-uno-reverse-lesbian",
        slug: "uno-reverse-lesbian",
        label: "Lesbian reverse",
        url: "/stickers/uno-reverse/lesbian.png",
        width: 512,
        height: 512,
        keywords: {
          en: ["lesbian", "uno", "reverse"],
          pt: ["lesbian", "uno", "reverso"],
        },
      },
      {
        id: "demo-sticker-uno-reverse-pansexual",
        slug: "uno-reverse-pansexual",
        label: "Pansexual reverse",
        url: "/stickers/uno-reverse/pansexual.png",
        width: 512,
        height: 512,
        keywords: {
          en: ["pansexual", "uno", "reverse"],
          pt: ["pansexual", "uno", "reverso"],
        },
      },
      {
        id: "demo-sticker-uno-reverse-asexual",
        slug: "uno-reverse-asexual",
        label: "Asexual reverse",
        url: "/stickers/uno-reverse/asexual.png",
        width: 512,
        height: 512,
        keywords: {
          en: ["asexual", "uno", "reverse"],
          pt: ["asexual", "uno", "reverso"],
        },
      },
      {
        id: "demo-sticker-uno-reverse-aromantic",
        slug: "uno-reverse-aromantic",
        label: "Aromantic reverse",
        url: "/stickers/uno-reverse/aromantic.png",
        width: 512,
        height: 512,
        keywords: {
          en: ["aromantic", "uno", "reverse"],
          pt: ["aromantic", "uno", "reverso"],
        },
      },
      {
        id: "demo-sticker-uno-reverse-nonbinary",
        slug: "uno-reverse-nonbinary",
        label: "Non-binary reverse",
        url: "/stickers/uno-reverse/nonbinary.png",
        width: 512,
        height: 512,
        keywords: {
          en: ["nonbinary", "uno", "reverse"],
          pt: ["nonbinary", "uno", "reverso"],
        },
      },
      {
        id: "demo-sticker-uno-reverse-genderfluid",
        slug: "uno-reverse-genderfluid",
        label: "Genderfluid reverse",
        url: "/stickers/uno-reverse/genderfluid.png",
        width: 512,
        height: 512,
        keywords: {
          en: ["genderfluid", "uno", "reverse"],
          pt: ["genderfluid", "uno", "reverso"],
        },
      },
      {
        id: "demo-sticker-uno-reverse-genderqueer",
        slug: "uno-reverse-genderqueer",
        label: "Genderqueer reverse",
        url: "/stickers/uno-reverse/genderqueer.png",
        width: 512,
        height: 512,
        keywords: {
          en: ["genderqueer", "uno", "reverse"],
          pt: ["genderqueer", "uno", "reverso"],
        },
      },
      {
        id: "demo-sticker-uno-reverse-agender",
        slug: "uno-reverse-agender",
        label: "Agender reverse",
        url: "/stickers/uno-reverse/agender.png",
        width: 512,
        height: 512,
        keywords: {
          en: ["agender", "uno", "reverse"],
          pt: ["agender", "uno", "reverso"],
        },
      },
    ],
  },
];
